labrintask/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from photo.views import home

from labrintask import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout, name='logout'),
    path('register/', include('users.urls', namespace='users')),
    # path('messages/', include('chat.urls')),
    path('photo/', include('photo.urls', namespace='photo')),
    path('', home, name='home')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.conf.urls import url
from django.urls import path, re_path


from photo import views

app_name = 'photo'
urlpatterns = [
    path('', views.photo_list, name='list'),
    path('upload/', views.upload_photo, name='upload'),
    path('allow/', views.allow_photo, name='allow'),
    re_path(r'^details/(?P<pk>\d+)/', views.photo_details, name='details'),
    re_path(r'^details/comment/edit/', views.comment_edit, name='edit'),
    re_path(r'^details/comment/delete/(?P<pk>\d+)/', views.comment_delete, name='delete'),
]

photo/models.py
from PIL import Image
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer

from labrintask import settings
from users.models import Users


class Photo(models.Model):
    users = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='users_photo')
    image = ThumbnailerImageField('Image', upload_to='users/image')


class PhotoSharing(models.Model):
    photo = models.ForeignKey(Photo, related_name='sharing_photo', on_delete=models.DO_NOTHING)
    users = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sharing_users', on_delete=models.DO_NOTHING)
    comment = models.BooleanField(default=False)


class Comment(models.Model):
    users = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='users_comment', on_delete=models.DO_NOTHING)
    photo = models.ForeignKey(Photo, related_name='photo_comment', on_delete=models.DO_NOTHING)
    comment = models.TextField('Comment')


@receiver(post_save, sender=Photo, dispatch_uid="photo_signal")
def photo_signal(sender, **kwargs):
    instance = kwargs.get('instance')
    if kwargs['created']:
        PhotoSharing.objects.create(users=instance.users, photo=Photo.objects.get(id=instance.id), comment=True)

    thumb_url = get_thumbnailer(instance.image).get_thumbnail(settings.options).url

photo/forms.py
from django import forms

from photo.models import Photo


class ComposeForm(forms.Form):
    comment = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
            )
        )


class UploadPhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        # fields = '__all__'
        exclude = ('users', )

photo/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.checks import messages
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from labrintask import settings
from photo.forms import ComposeForm, UploadPhotoForm
from photo.models import Photo, PhotoSharing, Comment
from photo.utils import generate_photo_thumnail_name
from users.models import Users


@login_required
def home(request):
    photo_data = []
    template = 'content.html'
    photo = Photo.objects.filter(users=request.user)
    for photo_item in photo:
        crop_url = generate_photo_thumnail_name(photo_item.image)
        data = {'id': photo_item.id, 'photo': photo_item.image, 'crop_url': crop_url}
        photo_data.append(data)

    users = Users.objects.all()
    return render(request, template, {'photo': photo_data, 'users': users})


def check_sharing(preview_user, user):
    list_id = []
    photo = Photo.objects.filter(users=Users.objects.get(email=preview_user))
    for photo_item in photo:
        list_id.append(photo_item.id)
    sharing = PhotoSharing.objects.filter(photo__in=photo, users=user)
    if sharing:
        return True
    else:
        return False


def check_sharing_photo(photo, user):
    photo = get_object_or_404(Photo, id=photo)
    sharing = PhotoSharing.objects.filter(photo=photo, users=user)
    if sharing:
        return True
    else:
        return False


def check_write_comment(photo, user):
    photo = get_object_or_404(Photo, id=photo)
    sharing = PhotoSharing.objects.filter(photo=photo, users=user)
    for sharing_item in sharing:
        return sharing_item.comment


@login_required
def photo_list(request):
    crop_data = []
    if 'user' in request.GET:
        preview_user = request.GET['user']
    else:
        raise Http404
    if not check_sharing(preview_user, request.user):
        raise PermissionDenied()
    else:
        template = 'photo.html'
        sharing = PhotoSharing.objects.filter(users=request.user, photo__users=Users.objects.get(email=preview_user))
        for sharing_item in sharing:
            crop_url = generate_photo_thumnail_name(sharing_item.photo.image)
            data = {'id': sharing_item.photo.id, 'photo': sharing_item.photo.image, 'crop_url': crop_url}
            crop_data.append(data)
        return render(request, template, {'photo': crop_data, 'users': Users.objects.get(email=preview_user)})


@login_required
def photo_details(request, pk):
    if not check_sharing_photo(pk, request.user):
        raise PermissionDenied()
    template = 'photo_details.html'
    photo = get_object_or_404(Photo, id=pk)
    form = ComposeForm()
    comments = Comment.objects.filter(photo=photo).order_by("id")
    write_comment = check_write_comment(pk, request.user)
    print(write_comment)
    content = {
        'photo': photo,
        'comments': comments,
        'form': form,
        'write_comment': write_comment
    }
    return render(request, template, content)


def check_delete_or_edit(user, comment, photo):
    if photo == None:
        if user == comment:
            return False
        else:
            return True
    else:
        if user == comment or user == photo:
            return False
        else:
            return True


@login_required
def comment_edit(request):
    if 'id' in request.GET:
        template = 'comment_edit_dialog.html'
        comments = Comment.objects.get(id=request.GET['id'])
        if check_delete_or_edit(request.user, comments.users, None):
            raise PermissionDenied
        # material_form = OrderMaterialForm(instance=material)
        form = ComposeForm(initial={'comment': comments.comment})
        if request.POST:
            if check_delete_or_edit(request.user, comments.users, None):
                raise PermissionDenied()
            comments.comment = request.POST['comment']
            comments.save()
        return render(request, template, {'form': form, 'comment_id': request.GET['id']})
    else:
        return Http404


@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, id=pk)
    if check_delete_or_edit(request.user, comment.users, comment.photo.users):
        raise PermissionDenied
    comment.delete()
    return HttpResponse("success")


@login_required
def upload_photo(request):
    template = 'uploadphoto.html'
    if request.POST:
        form = UploadPhotoForm(request.POST,request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.users = request.user
            f.save()
            return redirect('home')
    else:
        form = UploadPhotoForm()
    context = {
        'form': form
    }
    return render(request, template, context)


def check_allow(user, photo_user):
    if user == photo_user:
        return False
    else:
        return True


def bad_request(message):
    response = HttpResponse(json.dumps({'message': message}),
        content_type='application/json')
    response.status_code = 400
    return response


@login_required
def allow_photo(request):
    if request.GET:
        photo_id = request.GET['id']
        photo = Photo.objects.get(id=photo_id)
        email = request.GET['email']
        user = Users.objects.get(email=email)
        type = request.GET['type']
        if check_allow(request.user, photo.users):
            return bad_request(message='You do not have permission')
        else:
            if type == 'photo':
                if check_sharing_photo(photo_id, user):
                    return bad_request(message='Previously allowed')
                else:
                    PhotoSharing.objects.create(photo=photo, users=user, comment=False)
                    return HttpResponse("success")
            elif type == 'comment':
                if check_write_comment(photo_id, user):
                    return bad_request(message='Previously allowed')
                elif not check_sharing_photo(photo_id, user):
                    return bad_request(message='First allow the picture')
                else:
                    sharing = PhotoSharing.objects.filter(photo=photo, users=user)[0]
                    sharing.comment = True
                    sharing.save()
                    return HttpResponse("success")
    else:
        return HttpResponse("error")

photo/templates/base.html
<!DOCTYPE html>
{% load i18n staticfiles %}
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Labrin Home {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">



    <!-- Custom styles for this template -->
    <link href="{% static 'css/4-col-portfolio.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'photo:upload' %}">Upload Photo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">{{ user.email }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
         {% block content %}
         {% endblock %}
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% block script %}
    {% endblock %}

  </body>

</html>

photo/templates/comment_edit_dialog.html
{% load i18n thumbnail %}
<!-- Modal content -->
<style>

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content */
    .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 30px;
        border: 1px solid #888;
        width: max-content;
    }

    /* The Close Button */
    .close {
        color: #aaaaaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: #000;
        text-decoration: none;
        cursor: pointer;
    }
</style>
<div class="modal-content">
    <span class="close">&times;</span>
    <legend><h2>{% trans 'Comment Edit Dialog'%}</h2></legend>
    <form id="comment_edit_form" method="post">
        {% csrf_token %}
    {{ form.as_p }}
        <button class="btn btn-success" onclick="return form_submit('{{ comment_id }}')">Save</button>
        </form>
</div>

<script>
    // Get the modal
    var modal = document.getElementById('dialog_page');

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }

</script>

photo/templates/content.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

      <h4 class="my-4">Photo List
      </h4>
      {% for photo_item in photo %}
      <div class="col-md-4 portfolio-item">
          <div class="card h-100">
            <a href="{% url 'photo:details' photo_item.id %}"><img class="card-img-top" src="{{ photo_item.photo.url }}{{ photo_item.crop_url }}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'photo:details' photo_item.id %}">Project Five</a>
              </h4>
            </div>
          </div>
      </div>
      {% endfor %}

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

      <!-- Categories Widget -->
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-12">
              <ul class="list-unstyled mb-0">
                  {% for user in users %}
                <li>
                  <a href="{% url 'photo:list' %}?user={{ user.email }}">{{ user.email }}</a>
                </li>
                  {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </div>


    </div>

</div>
<!-- /.row -->
{% endblock %}

photo/templates/photo.html
{% extends 'base.html' %}
{% block content %}
<div class="row">

    <!-- Blog Entries Column -->
    <div class="col-md-8">

      <h4 class="my-4">{{ users.email }}
        <small>Photo list</small>
      </h4>
      {% for photo_item in photo %}
      <div class="col-md-4 portfolio-item">
          <div class="card h-100">
            <a href="{% url 'photo:details' photo_item.id %}"><img class="card-img-top" src="{{ photo_item.photo.url }}{{ photo_item.crop_url }}" alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <a href="{% url 'photo:details' photo_item.id %}">Project Five</a>
              </h4>
            </div>
          </div>
      </div>
      {% endfor %}

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>

    </div>

</div>
<!-- /.row -->
{% endblock %}

photo/templates/photo_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
<div class="col-md-8">
  <div class="card mt-4">
    <img class="card-img-top img-fluid" src="{{ photo.image.url }}" alt="">
    <div class="card-body">
      <h3 class="card-title">Photo Name</h3>
    </div>
  </div>
  <!-- /.card -->

  <div class="card card-outline-secondary my-4">
    <div class="card-header">
      Photo Comment
    </div>
    <div class="card-body">
        <div id="textHolder">
          {% for comment_item in comments %}
          <p class="edit{{ comment_item.id }}">{{ comment_item.comment }}
              {% if comment_item.users == user or comment_item.photo.users == user %}
              <button class="deleteItem" value="{{ comment_item.id }}" style="float:  right;"><i class="fas fa-minus-circle"></i></button>
              {% endif %}
            {% if comment_item.users == user %}
              <button onclick="return getEditDialog('{{ comment_item.id }}')" class="editItem" value="{{ comment_item.id }}" style="float:  right;margin-right: 5px;"> <i class="far fa-edit"></i></button>
            {% endif %}
          </p>

          <small class="text-muted comment{{ comment_item.id }}">Posted by {{ comment_item.users }}</small>

          <hr class="comment{{ comment_item.id }}">
            {% endfor %}
        </div>
    {% if write_comment %}
    <form id="comment" method="post">
        {% csrf_token %}
        <input type="hidden" id="email" value="{{ user.email }}">
        {{ form.as_p }}
        <input type="submit" class="btn btn-success">
    </form>
    {% endif %}
    </div>
  </div>
  <!-- /.card -->

</div>
<div class="col-md-4">
      <!-- Search Widget -->
      <div class="card my-4">
        <h5 class="card-header">Share and Permission</h5>
        <div class="card-body">
          <div class="input-group">
            <input type="email" id="allow_email" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <div class="col-md-12">
                      <button onclick="return allow_photo('{{ photo.id }}', 'photo')" class="btn btn-secondary btn-sm" type="button" style="margin-left: -15px;margin-top: 10px;">Allow Photo</button>
                      <button onclick="return allow_photo('{{ photo.id }}', 'comment')" class="btn btn-secondary btn-sm" type="button" style="margin-left: 55px;margin-top: 11px;">Allow Comment</button>
                </div>
            </span>
          </div>
        </div>
      </div>

</div>

</div>
    <div id="dialog_page" class="modal"></div>


{% endblock %}
{% block script %}
    <script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>
    <script>

        var loc = window.location;
        var textHolder = $("#textHolder");
        var txtInput = $("#id_comment");
        {#var email = $("#email").val();#}
        {#var last_id = $("#last_id")#}
        var formData = $("#comment");
        var wsStart = 'ws://';
        if (loc.protocol == 'https:'){
            wsStart = 'wss://'
        }
        var endpoint = wsStart + loc.host + loc.pathname;
        console.log(endpoint);
        var socket = new ReconnectingWebSocket(endpoint);
        socket.onmessage = function (e) {
            console.log("message", e);
            var chatDataMsg = JSON.parse(e.data);
            textHolder.append('<p>' + chatDataMsg.message + '<button class="deleteItem" value="'+ chatDataMsg.id + '" style="float:right;"><i class="fas fa-minus-circle"></i></button><button value="'+ chatDataMsg.id + '" style="float:  right;margin-right: 5px;"> <i class="far fa-edit"></i></button></p>' + '<small class="text-muted comment' + chatDataMsg.id + '">Posted by ' + chatDataMsg.username +'</small><hr class="comment' + chatDataMsg.id + '">')
        };

        socket.onopen = function (e) {
            console.log("open", e);
            formData.submit(function (event) {
                event.preventDefault();
                var msg = txtInput.val();
                {#var id = last_id.val();#}
                {#textHolder.append('<p>' + msg + '</p>' + '<small class="text-muted">Posted by ' + email +'</small><hr>');#}
                var finalData = {
                    'message': msg,
                };
                socket.send(JSON.stringify(finalData));
                formData[0].reset()
            })

        };

        socket.onerror = function (e) {
            console.log("error", e)
        };

        socket.onclose = function (e) {
            console.log("close", e)

        };
    $(".deleteItem").click(function() {
        var commentContainer = $(this).parent();
        // language=JQuery-CSS
        var post = $(".comment" + $(this).val());
            $.ajax({
                type: 'GET',
                url: '/photo/details/comment/delete/' + $(this).val(),
                success: function(){
                    commentContainer.slideUp('slow', function() {$(this).remove();});
                    $('#load').fadeOut();
                    post.remove();
                },
                error: function(){
                    alert("403 Forbidden");
                },
            });
    });
    </script>

    <script>
        function getEditDialog(id) {
            $.ajax({
                url: "{% url 'photo:edit' %}" + "?id="+id
            }).then(function(data) {
                $('#dialog_page').html(data);
                var modal = document.getElementById('dialog_page');
                modal.style.display = "block";
            });
        }

        function form_submit(id) {
        var data = $('#comment_edit_form').serialize();
            $.ajax({
                type: 'POST',
                url: "{% url 'photo:edit' %}"+"?id="+ id,
                data: data,
                success: function (data) {
                    console.log("success message");
                }, error: function (request, status, error) {
                    alert(status);
                    console.log(request);
                    alert(error);
                }
            });
        }

        function allow_photo(id, type) {
            {#var email = document.getElementById("searchTxt").value;#}
            var email = $("#allow_email");
            $.ajax({
                type: 'GET',
                url: "{% url 'photo:allow' %}"+"?email=" + email.val() + "&type=" + type + "&id=" + id,
                success: function (data) {
                    alert("Successful");
                }, error: function (request, status, error) {
                    alert(status);
                    console.log(request);
                    var err = JSON.parse(request.responseText);
                    alert(err.message);
                }
            });
        }

    </script>


{% endblock %}

photo/templates/uploadphoto.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-8">
    <h3 class="my-4">Select Photo</h3>
  <form method="post" action="{% url 'photo:upload' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
          <label class="control-label">{{ field.label_tag }}</label>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
<p></p>
</div>
{% endblock %}